# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'secondmain.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(503, 403)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.toolButton_searchCourse = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_searchCourse.setGeometry(QtCore.QRect(100, 30, 111, 22))
        self.toolButton_searchCourse.setObjectName("toolButton_searchCourse")
        self.toolButton_createCourse = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_createCourse.setGeometry(QtCore.QRect(270, 30, 121, 22))
        self.toolButton_createCourse.setObjectName("toolButton_createCourse")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(100, 110, 291, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton_enterClass = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_enterClass.setGeometry(QtCore.QRect(190, 310, 113, 32))
        self.pushButton_enterClass.setObjectName("pushButton_enterClass")
        self.label_classList = QtWidgets.QLabel(self.centralwidget)
        self.label_classList.setGeometry(QtCore.QRect(210, 80, 60, 16))
        self.label_classList.setObjectName("label_classList")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolButton_searchCourse.setText(_translate("MainWindow", "클래스 검색"))
        self.toolButton_createCourse.setText(_translate("MainWindow", "클래스 생성"))
        self.pushButton_enterClass.setText(_translate("MainWindow", "클래스 입장"))
        self.label_classList.setText(_translate("MainWindow", "클래스 목록"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
