# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grade_homework.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_homeworkTitle = QtWidgets.QLabel(Dialog)
        self.label_homeworkTitle.setGeometry(QtCore.QRect(130, 30, 60, 16))
        self.label_homeworkTitle.setObjectName("label_homeworkTitle")
        self.label_studentName = QtWidgets.QLabel(Dialog)
        self.label_studentName.setGeometry(QtCore.QRect(230, 30, 60, 16))
        self.label_studentName.setObjectName("label_studentName")
        self.label_gradeHomework = QtWidgets.QLabel(Dialog)
        self.label_gradeHomework.setGeometry(QtCore.QRect(170, 60, 60, 16))
        self.label_gradeHomework.setObjectName("label_gradeHomework")
        self.label_title = QtWidgets.QLabel(Dialog)
        self.label_title.setGeometry(QtCore.QRect(40, 90, 60, 16))
        self.label_title.setObjectName("label_title")
        self.lineEdit_title = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_title.setGeometry(QtCore.QRect(100, 90, 221, 21))
        self.lineEdit_title.setObjectName("lineEdit_title")
        self.label_content = QtWidgets.QLabel(Dialog)
        self.label_content.setGeometry(QtCore.QRect(40, 120, 60, 16))
        self.label_content.setObjectName("label_content")
        self.textEdit_content = QtWidgets.QTextEdit(Dialog)
        self.textEdit_content.setGeometry(QtCore.QRect(100, 120, 221, 111))
        self.textEdit_content.setObjectName("textEdit_content")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_homeworkTitle.setText(_translate("Dialog", "과제1"))
        self.label_studentName.setText(_translate("Dialog", "학생A"))
        self.label_gradeHomework.setText(_translate("Dialog", "과제 채점"))
        self.label_title.setText(_translate("Dialog", "제목"))
        self.label_content.setText(_translate("Dialog", "내용"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
