# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'upload_homework.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_courseName = QtWidgets.QLabel(Dialog)
        self.label_courseName.setGeometry(QtCore.QRect(130, 30, 60, 16))
        self.label_courseName.setObjectName("label_courseName")
        self.label_teacherName = QtWidgets.QLabel(Dialog)
        self.label_teacherName.setGeometry(QtCore.QRect(230, 30, 60, 16))
        self.label_teacherName.setObjectName("label_teacherName")
        self.label_uploadHomework = QtWidgets.QLabel(Dialog)
        self.label_uploadHomework.setGeometry(QtCore.QRect(170, 60, 60, 16))
        self.label_uploadHomework.setObjectName("label_uploadHomework")
        self.label_title = QtWidgets.QLabel(Dialog)
        self.label_title.setGeometry(QtCore.QRect(40, 90, 60, 16))
        self.label_title.setObjectName("label_title")
        self.lineEdit_title = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_title.setGeometry(QtCore.QRect(100, 90, 221, 21))
        self.lineEdit_title.setObjectName("lineEdit_title")
        self.label_content = QtWidgets.QLabel(Dialog)
        self.label_content.setGeometry(QtCore.QRect(40, 120, 60, 16))
        self.label_content.setObjectName("label_content")
        self.textEdit_content = QtWidgets.QTextEdit(Dialog)
        self.textEdit_content.setGeometry(QtCore.QRect(100, 120, 221, 111))
        self.textEdit_content.setObjectName("textEdit_content")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_courseName.setText(_translate("Dialog", "수학"))
        self.label_teacherName.setText(_translate("Dialog", "홍길동"))
        self.label_uploadHomework.setText(_translate("Dialog", "과제 등록"))
        self.label_title.setText(_translate("Dialog", "제목"))
        self.label_content.setText(_translate("Dialog", "내용"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
