# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search_class.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(503, 403)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(100, 161, 291, 141))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton_joinClass = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_joinClass.setGeometry(QtCore.QRect(190, 310, 113, 32))
        self.pushButton_joinClass.setObjectName("pushButton_joinClass")
        self.label_classList = QtWidgets.QLabel(self.centralwidget)
        self.label_classList.setGeometry(QtCore.QRect(210, 130, 60, 16))
        self.label_classList.setObjectName("label_classList")
        self.lineEdit_searchClass = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_searchClass.setGeometry(QtCore.QRect(110, 90, 211, 21))
        self.lineEdit_searchClass.setObjectName("lineEdit_searchClass")
        self.pushButton_searchClass = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_searchClass.setGeometry(QtCore.QRect(330, 86, 65, 32))
        self.pushButton_searchClass.setObjectName("pushButton_searchClass")
        self.label_searchClass = QtWidgets.QLabel(self.centralwidget)
        self.label_searchClass.setGeometry(QtCore.QRect(210, 50, 60, 16))
        self.label_searchClass.setObjectName("label_searchClass")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_joinClass.setText(_translate("MainWindow", "클래스 가입"))
        self.label_classList.setText(_translate("MainWindow", "클래스 목록"))
        self.pushButton_searchClass.setText(_translate("MainWindow", "검색"))
        self.label_searchClass.setText(_translate("MainWindow", "클래스 검색"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
