# Form implementation generated from reading ui file 'c:\Users\HERE\Desktop\Object-Oriented-Analysis-Design\HW.4\newUI\grade_homework.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_homeworkTitle = QtWidgets.QLabel(parent=Dialog)
        self.label_homeworkTitle.setGeometry(QtCore.QRect(130, 30, 60, 16))
        self.label_homeworkTitle.setObjectName("label_homeworkTitle")
        self.label_studentName = QtWidgets.QLabel(parent=Dialog)
        self.label_studentName.setGeometry(QtCore.QRect(230, 30, 60, 16))
        self.label_studentName.setObjectName("label_studentName")
        self.label_gradeHomework = QtWidgets.QLabel(parent=Dialog)
        self.label_gradeHomework.setGeometry(QtCore.QRect(170, 60, 60, 16))
        self.label_gradeHomework.setObjectName("label_gradeHomework")
        self.label_score = QtWidgets.QLabel(parent=Dialog)
        self.label_score.setGeometry(QtCore.QRect(40, 90, 60, 16))
        self.label_score.setObjectName("label_score")
        self.lineEdit_score = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_score.setGeometry(QtCore.QRect(100, 90, 221, 21))
        self.lineEdit_score.setObjectName("lineEdit_score")
        self.label_comment = QtWidgets.QLabel(parent=Dialog)
        self.label_comment.setGeometry(QtCore.QRect(40, 120, 60, 16))
        self.label_comment.setObjectName("label_comment")
        self.textEdit_comment = QtWidgets.QTextEdit(parent=Dialog)
        self.textEdit_comment.setGeometry(QtCore.QRect(100, 120, 221, 111))
        self.textEdit_comment.setObjectName("textEdit_comment")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_homeworkTitle.setText(_translate("Dialog", "과제1"))
        self.label_studentName.setText(_translate("Dialog", "학생A"))
        self.label_gradeHomework.setText(_translate("Dialog", "과제 채점"))
        self.label_score.setText(_translate("Dialog", "점수"))
        self.label_comment.setText(_translate("Dialog", "내용"))
